namespace Hydra.Crm.Core.Constants
{
    public static class SalePermissionTypes
    {
        public const string SALE_CATEGORY_MANAGEMENT = "SALE.CATEGORY_MANAGEMENT";
        public const string SALE_PRODUCT_ATTRIBUTE_MANAGEMENT = "SALE.PRODUCT_ATTRIBUTE_MANAGEMENT";
        public const string SALE_ORDER_MANAGEMENT = "SALE.ORDER_MANAGEMENT";
        public const string SALE_ORDER_DISCOUNT_MANAGEMENT = "SALE.ORDER_DISCOUNT_MANAGEMENT";
        public const string SALE_ORDER_ITEM_MANAGEMENT = "SALE.ORDER_ITEM_MANAGEMENT";
        public const string SALE_ORDERNOTE_MANAGEMENT = "SALE.ORDERNOTE_MANAGEMENT";
        public const string SALE_PAYMENT_MANAGEMENT = "SALE.PAYMENT_MANAGEMENT";
        public const string SALE_PRODUCT_MANAGEMENT = "SALE.PRODUCT_MANAGEMENT";
        public const string SALE_PRODUCT_INVENTORY_MANAGEMENT = "SALE.PRODUCT_INVENTORY_MANAGEMENT";
        public const string SALE_PRODUCT_REVIEW_MANAGEMENT = "SALE.PRODUCT_REVIEW_MANAGEMENT";
        public const string SALE_PRODUCT_REVIEW_HELPFULNESS_MANAGEMENT = "SALE.PRODUCT_REVIEW_HELPFULNESS_MANAGEMENT";
        public const string SALE_PRODUCT_TAG_MANAGEMENT = "SALE.PRODUCT_TAG_MANAGEMENT";
        public const string SALE_SEARCH_TERM_MANAGEMENT = "SALE.SEARCH_TERM_MANAGEMENT";
        public const string SALE_SHIPMENT_MANAGEMENT = "SALE.SHIPMENT_MANAGEMENT";
        public const string SALE_SHOPPING_CART_MANAGEMENT = "SALE.SHOPPING_CART_MANAGEMENT";
        public const string SALE_CURRENCY_MANAGEMENT = "SALE.CURRENCY_MANAGEMENT";
        public const string SALE_DELIVERY_MANAGEMENT = "SALE.DELIVERY_MANAGEMENT";
        public const string SALE_DISCOUNT_MANAGEMENT = "SALE.DISCOUNT_MANAGEMENT";
        public const string SALE_MANUFACTURER_MANAGEMENT = "SALE.MANUFACTURER_MANAGEMENT";
        public const string SALE_SHIPMENT_METHOD_MANAGEMENT = "SALE.SHIPMENT_METHOD_MANAGEMENT";
        public const string SALE_COUNTRY_MANAGEMENT = "SALE.COUNTRY_MANAGEMENT";
        public const string SALE_STATE_PROVINCE_MANAGEMENT = "SALE.STATE_PROVINCE_MANAGEMENT";
        public const string SALE_ADDRESS_MANAGEMENT = "SALE.ADDRESS_MANAGEMENT";
        public const string SALE_TAX_MANAGEMENT = "SALE.TAX_MANAGEMENT";

    }
}
