using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hydra.Ecommerce.Core.EntityConfiguration
{
    public class ProductConfiguration : IEntityTypeConfiguration<Hydra.Ecommerce.Core.Domain.Product>
    {
        public void Configure(EntityTypeBuilder<Hydra.Ecommerce.Core.Domain.Product> entity)
        {
            entity.ToTable("Product", "Sale");

            entity.HasIndex(e => new { e.Published, e.Deleted, e.Id }, "IX_Product_Deleted_and_Published");

            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(100);
            entity.Property(e => e.Sku)
            .IsRequired()
            .HasMaxLength(70);
            entity.Property(e => e.AdminComment).HasMaxLength(300);
            entity.Property(e => e.AvailableEndDateTimeUtc).HasPrecision(6);
            entity.Property(e => e.AvailableStartDateTimeUtc).HasPrecision(6);
            entity.Property(e => e.CreatedOnUtc).HasPrecision(6);
            entity.Property(e => e.UpdatedOnUtc).HasPrecision(6);
            entity.Property(e => e.MarkAsNewEndDateTimeUtc).HasPrecision(6);
            entity.Property(e => e.MarkAsNewStartDateTimeUtc).HasPrecision(6);
            entity.Property(e => e.MetaDescription).HasMaxLength(300);
            entity.Property(e => e.MetaKeywords).HasMaxLength(300);
            entity.Property(e => e.MetaTitle).HasMaxLength(100);
            entity.Property(e => e.OldSellUnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.SellUnitPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.ShortDescription).HasMaxLength(300);

            entity.HasOne(d => d.TaxCategory).WithMany(p => p.Products)
            .HasForeignKey(d => d.TaxCategoryId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_Product_TaxCategory");

            entity.HasOne(d => d.ImagePreview).WithMany()
                .HasForeignKey(d => d.ImagePreviewId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Product_ImagePreview");

            entity.HasOne(d => d.CreateUser).WithMany()
            .HasForeignKey(d => d.CreateUserId)
            .HasConstraintName("FK_Product_CreateUser");

            entity.HasOne(d => d.UpdateUser).WithMany()
            .HasForeignKey(d => d.UpdateUserId)
            .HasConstraintName("FK_Product_UpdateUser");

            entity.HasOne(a => a.ImagePreview)
               .WithMany() // Leave empty if FileUpload doesn't have a collection of Articles
               .HasForeignKey(a => a.ImagePreviewId)
               .IsRequired(false)
               .OnDelete(DeleteBehavior.SetNull);

            // Seed sample products from provided example JSON using entity.HasData
            entity.HasData(
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1000,
                    Sku = "BOOK-1000",
                    Name = "Wireless Noise-Cancelling Headphones",
                    MetaKeywords = "bestseller,trending",
                    MetaTitle = "Wireless Noise-Cancelling Headphones",
                    ShortDescription = "ANC Headphones • 30hr Battery",
                    FullDescription = "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Perfect for music lovers and professionals.",
                    MetaDescription = "ANC Headphones • 30hr Battery",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 45,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 249.99m,
                    OldSellUnitPrice = 349.99m,
                    DisplayOrder = 1,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 324,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    ImagePreviewId = null,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    UpdateUserId = null,
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number,

                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1001,
                    Sku = "ELECTRONIK-1001",
                    Name = "Smart Watch Pro",
                    MetaKeywords = "new,popular",
                    MetaTitle = "Smart Watch Pro",
                    ShortDescription = "AMOLED Display • GPS • Health",
                    FullDescription = "Advanced smartwatch with health monitoring, GPS tracking, and a stunning AMOLED display. Water resistant to 50m.",
                    MetaDescription = "AMOLED Display • GPS • Health",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 32,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 299.99m,
                    OldSellUnitPrice = 399.99m,
                    DisplayOrder = 2,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 218,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1002,
                    Sku = "ELECTRONIK-1002",
                    Name = "Portable Bluetooth Speaker",
                    MetaKeywords = "sale",
                    MetaTitle = "Portable Bluetooth Speaker",
                    ShortDescription = "Waterproof • 360° Sound",
                    FullDescription = "Compact, waterproof speaker with 360-degree sound. 12-hour battery life and built-in microphone.",
                    MetaDescription = "Waterproof • 360° Sound",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 78,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 79.99m,
                    OldSellUnitPrice = 119.99m,
                    DisplayOrder = 3,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 156,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = false,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1003,
                    Sku = "ELECTRONIK-1003",
                    Name = "Mechanical Keyboard RGB",
                    MetaKeywords = "popular",
                    MetaTitle = "Mechanical Keyboard RGB",
                    ShortDescription = "Hot-Swap • RGB • Aluminum",
                    FullDescription = "Full-size mechanical keyboard with customizable RGB lighting, hot-swappable switches, and premium build quality.",
                    MetaDescription = "Hot-Swap • RGB • Aluminum",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 23,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 149.99m,
                    OldSellUnitPrice = 189.99m,
                    DisplayOrder = 4,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 189,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = false,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1004,
                    Sku = "FASHION-1004",
                    Name = "Classic Leather Jacket",
                    MetaKeywords = "bestseller,trending",
                    MetaTitle = "Classic Leather Jacket",
                    ShortDescription = "Genuine Leather • Slim Fit",
                    FullDescription = "Timeless genuine leather jacket with premium lining. A wardrobe essential that pairs with everything.",
                    MetaDescription = "Genuine Leather • Slim Fit",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 15,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 189.99m,
                    OldSellUnitPrice = 279.99m,
                    DisplayOrder = 5,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 412,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = true,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1005,
                    Sku = "FASION-1005",
                    Name = "Premium Cotton T-Shirt",
                    MetaKeywords = "sale,sustainable",
                    MetaTitle = "Premium Cotton T-Shirt",
                    ShortDescription = "Organic Cotton • Relaxed Fit",
                    FullDescription = "Ultra-soft 100% organic cotton t-shirt. Comfortable, breathable, and sustainably made.",
                    MetaDescription = "Organic Cotton • Relaxed Fit",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 120,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 39.99m,
                    OldSellUnitPrice = 59.99m,
                    DisplayOrder = 6,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 287,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = false,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1006,
                    Sku = "HOME-1006",
                    Name = "Designer Sunglasses",
                    MetaKeywords = "popular,new",
                    MetaTitle = "Designer Sunglasses",
                    ShortDescription = "Polarized • UV400 • Titanium",
                    FullDescription = "UV400 protection with polarized lenses. Lightweight titanium frame for all-day comfort.",
                    MetaDescription = "Polarized • UV400 • Titanium",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 56,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 129.99m,
                    OldSellUnitPrice = 179.99m,
                    DisplayOrder = 7,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 165,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = true,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1007,
                    Sku = "HOME-1007",
                    Name = "Minimalist Desk Lamp",
                    MetaKeywords = "trending",
                    MetaTitle = "Minimalist Desk Lamp",
                    ShortDescription = "LED • Touch Control • Wireless Charging",
                    FullDescription = "LED desk lamp with adjustable color temperature, touch controls, and wireless charging base.",
                    MetaDescription = "LED • Touch Control • Wireless Charging",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 34,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 89.99m,
                    OldSellUnitPrice = 129.99m,
                    DisplayOrder = 8,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 143,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = true,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1008,
                    Sku = "HOME-1008",
                    Name = "Ceramic Plant Pot Set",
                    MetaKeywords = "popular,new",
                    MetaTitle = "Ceramic Plant Pot Set",
                    ShortDescription = "Set of 3 • Matte Finish • Handmade",
                    FullDescription = "Set of 3 handcrafted ceramic plant pots in matte finish. Perfect for succulents and small plants.",
                    MetaDescription = "Set of 3 • Matte Finish • Handmade",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 67,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 44.99m,
                    OldSellUnitPrice = 64.99m,
                    DisplayOrder = 9,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 211,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = false,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1009,
                    Sku = "SPORT-1009",
                    Name = "Yoga Mat Premium",
                    MetaKeywords = "bestseller",
                    MetaTitle = "Yoga Mat Premium",
                    ShortDescription = "6mm Thick • Non-Slip • Eco-TPE",
                    FullDescription = "Extra thick non-slip yoga mat with alignment guides. Eco-friendly TPE material.",
                    MetaDescription = "6mm Thick • Non-Slip • Eco-TPE",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 45,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 49.99m,
                    OldSellUnitPrice = 69.99m,
                    DisplayOrder = 10,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 234,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1010,
                    Sku = "BEAUTY-1010",
                    Name = "Skincare Essential Kit",
                    MetaKeywords = "bestseller,new",
                    MetaTitle = "Skincare Essential Kit",
                    ShortDescription = "4-Piece Set • All Skin Types",
                    FullDescription = "Complete skincare routine with cleanser, toner, serum, and moisturizer. For all skin types.",
                    MetaDescription = "4-Piece Set • All Skin Types",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 38,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 89.99m,
                    OldSellUnitPrice = 129.99m,
                    DisplayOrder = 11,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 267,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = true,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = true,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                },
                new Hydra.Ecommerce.Core.Domain.Product
                {
                    Id = 1011,
                    Sku = "BOOK-1011",
                    Name = "The Art of Modern Living",
                    MetaKeywords = "bestseller",
                    MetaTitle = "The Art of Modern Living",
                    ShortDescription = "Hardcover • 320 Pages",
                    FullDescription = "A comprehensive guide to interior design, minimalism, and creating spaces that inspire.",
                    MetaDescription = "Hardcover • 320 Pages",
                    TaxCategoryId = 1,
                    StockType = Enums.StockType.Total,
                    StockQuantity = 65,
                    MinStockQuantity = 0,
                    NotifyAdminForQuantityBelow = false,
                    OrderMinimumQuantity = 1,
                    OrderMaximumQuantity = 1000,
                    SellUnitPrice = 34.99m,
                    OldSellUnitPrice = 49.99m,
                    DisplayOrder = 12,
                    ApprovedRatingSum = 0,
                    NotApprovedRatingSum = 0,
                    ApprovedTotalReviews = 178,
                    NotApprovedTotalReviews = 0,
                    HasDiscountsApplied = false,
                    MarkAsNew = false,
                    NotReturnable = false,
                    AllowedQuantities = false,
                    IsTaxExempt = false,
                    ShowOnHomepage = false,
                    IsFreeShipping = false,
                    AllowCustomerReviews = true,
                    DisplayStockQuantity = false,
                    DisableBuyButton = false,
                    DisableWishlistButton = false,
                    AvailableForPreOrder = false,
                    CallForPrice = false,
                    Published = true,
                    Deleted = false,
                    CreateUserId = 1,
                    CreatedOnUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    AvailableStartDateTimeUtc = DateTime.SpecifyKind(DateTime.Parse("2026-4-23"), DateTimeKind.Utc),
                    DeliveryDateType = Enums.DeliveryDateType.ThreeDays,
                    CurrencyType = Enums.CurrencyType.Dollar,
                    MeasureType = Enums.MeasureType.Number
                }
            );

           // Seed product-category mappings for example products

           //entity.HasData(
           //    new ProductCategory { Id = 6000, ProductId = 1000, CategoryId = 3, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6001, ProductId = 1001, CategoryId = 3, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6002, ProductId = 1002, CategoryId = 3, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6003, ProductId = 1003, CategoryId = 3, DisplayOrder = 1 },

           //    new ProductCategory { Id = 6004, ProductId = 1004, CategoryId = 4, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6005, ProductId = 1005, CategoryId = 4, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6006, ProductId = 1006, CategoryId = 4, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6007, ProductId = 1007, CategoryId = 4, DisplayOrder = 1 },

           //    new ProductCategory { Id = 6008, ProductId = 1007, CategoryId = 5, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6009, ProductId = 1008, CategoryId = 5, DisplayOrder = 1 },

           //    new ProductCategory { Id = 6010, ProductId = 1009, CategoryId = 6, DisplayOrder = 1 },

           //    new ProductCategory { Id = 6011, ProductId = 1010, CategoryId = 7, DisplayOrder = 1 },
           //    new ProductCategory { Id = 6012, ProductId = 1011, CategoryId = 8, DisplayOrder = 1 }
           //);

           //// Seed product - tag mappings (example data)
           //entity.HasData(
           //    new ProductProductTag { Id = 3000, ProductId = 1000, ProductTagId = 1 },
           //    new ProductProductTag { Id = 3001, ProductId = 1000, ProductTagId = 6 },
           //    new ProductProductTag { Id = 3002, ProductId = 1001, ProductTagId = 2 },
           //    new ProductProductTag { Id = 3003, ProductId = 1001, ProductTagId = 3 },
           //    new ProductProductTag { Id = 3004, ProductId = 1002, ProductTagId = 4 },
           //    new ProductProductTag { Id = 3005, ProductId = 1003, ProductTagId = 3 },
           //    new ProductProductTag { Id = 3006, ProductId = 1004, ProductTagId = 1 },
           //    new ProductProductTag { Id = 3007, ProductId = 1004, ProductTagId = 6 },
           //    new ProductProductTag { Id = 3008, ProductId = 1005, ProductTagId = 4 },
           //    new ProductProductTag { Id = 3009, ProductId = 1005, ProductTagId = 5 },
           //    new ProductProductTag { Id = 3010, ProductId = 1006, ProductTagId = 3 },
           //    new ProductProductTag { Id = 3011, ProductId = 1006, ProductTagId = 2 },
           //    new ProductProductTag { Id = 3012, ProductId = 1007, ProductTagId = 6 },
           //    new ProductProductTag { Id = 3013, ProductId = 1008, ProductTagId = 3 },
           //    new ProductProductTag { Id = 3014, ProductId = 1008, ProductTagId = 2 },
           //    new ProductProductTag { Id = 3015, ProductId = 1009, ProductTagId = 1 },
           //    new ProductProductTag { Id = 3016, ProductId = 1010, ProductTagId = 1 },
           //    new ProductProductTag { Id = 3017, ProductId = 1010, ProductTagId = 2 },
           //    new ProductProductTag { Id = 3018, ProductId = 1011, ProductTagId = 1 }
           //);
        }
    }
}
